apiVersion: v1
kind: Service
metadata:
  labels:
    cicd.hooli.com/environment: nucleus
    cicd.hooli.com/k8s-namespace: nucleus
  name: frontend
  namespace: nucleus
spec:
  ports:
  - name: pprof
    port: 6060
    protocol: TCP
    targetPort: 6060
  - name: api
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: frontend
